### ISSUE TITLE
2.0.0 -> 2.0.1 includes breaking change

### ISSUE THREAD

**Issue by znewton** [AlaskaAirlines/OrionIcons#22]
**Describe the bug**
When upgrading from orion-icons `2.0.0` to `2.1.1` (a minor upgrade) I ran into an error on build stating that `~@alaskaairux/orion-icons/dist/tokens/TokenVariables` no longer exists.
![image](https://user-images.githubusercontent.com/14362200/76575404-3d933000-647c-11ea-9758-be3e6a1fee00.png)
Upon further investigation, I found that this breaking change was introduced in `2.0.1` (a patch).

**To Reproduce**
1. Run `npm i @alaskaairux/orion-icons@2.0.0`
2. Add `@import '~@alaskaairux/orion-icons/dist/tokens/TokenVariables` to a `.scss` file in your project; see that build passes
3. Run `npm update`
4. See above mentioned error

**Expected behavior**
I would expect that a patch would not break consumption of orion-icons

**Additional context**
To resolve for our project, we have version locked all our @alaskaairux dependencies until we are ready to do the full auro upgrade

**Comment by blackfalcon** [comment]
This issue needs to be researched and documented as to exactly what lead to this type of release. What was released and when and how can this be done better. 

A clear takeaway is that the Auro team needs to get better at coupled releases where there is a clear dependency. 

In this case, the dependency that was lacking was that the new Icons repo did not alert the user that the Tokens repo needed to be updated to a specific version too.

**Comment by blackfalcon** [comment]
This issue was reviewed and steps are being taken to ensure that this never happens again.
