### ISSUE TITLE
Generate sass based on the icon json file

### ISSUE THREAD

**Issue by c-n-d** [AlaskaAirlines/OrionIcons#6]
# Issue report

## Expected Behavior
1. [src/_orion-icons.scss](https://github.com/AlaskaAirlines/OrionIcons/blob/master/src/_orion-icons.scss) should not require manual edits to support new icons.

## Current Behavior
1. [src/_orion-icons.scss](https://github.com/AlaskaAirlines/OrionIcons/blob/master/src/_orion-icons.scss) does not include all icons and requires manual changes to support new icons.

## Possible Solution
1. Use [src/data/orion-icons.json](https://github.com/AlaskaAirlines/OrionIcons/blob/master/src/data/orion-icons.json) to generate the sass file.

## Context
1. Reduces the possibility for error when editing the sass file.

**Comment by blackfalcon** [comment]
Prepare icons for Auro #14
